/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package repositoriodenis;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void Suma(){
        App classSuma = new App();
        assertEquals(4, classSuma.sumar(2, 2));
    }
    @Test void Resta(){
        App classSuma = new App();
        assertEquals(4, classSuma.restar(2, 2));
    }
    @Test void Multiplicacion(){
        App classSuma = new App();
        assertEquals(4, classSuma.multiplicar(2, 2));
    }
    @Test void Division(){
        App classSuma = new App();
        assertEquals(4, classSuma.dividir(2, 2));
    }
}
